- src/app/skatecast/AvatarList.tsx
- src/app/skatecast/CommentItem.tsx
- src/app/skatecast/CommentsList.tsx
- src/app/skatecast/PostBox.tsx
- src/app/skatecast/page.tsx
- src/components/Navbar/utils/checkReward.tsx
> refactor: SkateCastComponent

- src/app/Cursor/Cursor.module.css
- src/app/Cursor/Cursor.tsx
> fix: cursor cursor fixed up

- src/app/skatecast/components/PostBox.tsx
> Fix: ComponentPostBox

- src/app/Cursor/Cursor.module.css
- src/app/Cursor/Cursor.tsx
- src/app/Cursor/global.css
- src/app/layout.tsx
Correcao do component cursor bugadoDAO
> fix: CursorPersonalizarBugado

- src/app/map/EmbeddedCommentList.tsx
- src/app/map/UploadForm.tsx
- src/app/map/page.tsx
- src/components/Navbar/sideBarMobile.tsx
- src/components/Navbar/sidebarDesktop.tsx
> adding a map component

- src/app/map/UploadForm.tsx
- src/app/map/page.tsx
> stylized Map component fixes

- src/app/mainFeed/components/CommentItem.tsx
- src/app/map/EmbeddedCommentList.tsx
- src/app/map/UploadForm.tsx
- src/app/map/page.tsx
animation corrections were made, map component is still being made to extract the metadata from the coordinates, web--gnar will help me as it goes
> fixing component and making component coordinate map

- src/app/map/page.tsx
- src/app/wallet/components/TotalWalletPage.tsx
- src/app/wallet/page.tsx
- src/components/Navbar/sideBarMobile.tsx
- src/components/Navbar/sidebarDesktop.tsx
- src/styles/fonts.css
> font stylizations being done

- src/components/Navbar/sideBarMobile.tsx
https://github.com/user-attachments/assets/15c70438-9c48-4572-a8be-d9df309a5b56
> navigation bar is closed when you click on a navigation route

- src/app/post/[...slug]/page.tsx
- src/components/Skater/SkaterHeader.tsx
> send button fixed

- src/app/mainFeed/components/CommentItem.tsx
- src/app/mainFeed/components/EditCommentModal.tsx
- src/app/mainFeed/components/replyModal.tsx
- src/components/MagColumn/index.tsx
- src/hooks/comments.ts
> changes in the edit magcolum button

- src/app/wallet/components/pix.tsx
- src/app/wallet/components/sendHBDModal.tsx
> modal and pix tweaked

- src/app/wallet/components/pix.tsx
- src/app/wallet/components/sendHBDModal.tsx
https://github.com/user-attachments/assets/b3f5b62c-d35c-430e-9a36-33edbb484e18
> pix and modal working

- src/app/mainFeed/components/CommentItem.tsx
- src/app/mainFeed/components/ToggleComments.tsx
before
after
https://github.com/user-attachments/assets/f5b620cc-1714-4e75-a6a7-abbe51ef6f47
> changes to make comments and see commentss

- package.json
- src/app/wallet/components/pix.tsx
- src/app/wallet/components/sendHBDModal.tsx
> mudancas feitas no pix

- src/app/wallet/components/HiveModals.tsx
- src/app/wallet/components/Modals/isDepositHbdSavingsModalOpened.tsx
- src/app/wallet/components/Modals/isHPPowerModalOpened.tsx
- src/app/wallet/components/Modals/isHbdModalOpened.tsx
- src/app/wallet/components/Modals/isHiveModalsOpen.tsx
- src/app/wallet/components/hiveWallet.tsx
> hive wallet done

- src/app/map/UploadForm.tsx
- src/app/map/page.tsx
- src/app/profile/[username]/page.tsx
- src/app/wallet/components/sendHBDModal.tsx
- src/components/Profile/ProfileHeader.tsx
- src/components/Profile/profileDashboard.tsx
- src/components/Profile/profileTabs.tsx
> some changes to the component profile

- src/app/notifications/components/TransactionHistory.tsx
- src/app/wallet/components/LimitesTable.tsx
- src/app/wallet/components/pix.tsx
- src/app/wallet/components/sendHBDModal.tsx
> mudancas no pix feitas

- package.json
- src/app/mainFeed/page.tsx
fixes #84 
closes #84 
fully tested, works well on all screen sizes.
> feat: option to add emoji in post text

- .vscode/launch.json
now you will be able to debug using vscode
> feat: add launch.json for vscode debug

- src/app/wallet/components/LimitesTable.tsx
- src/app/wallet/components/pix.tsx
- src/app/wallet/components/sendHBDModal.tsx
- src/components/Hive/Login/LoginModal.tsx
- src/components/PostCard/HiveTipModal.tsx
- src/components/PostCard/TipButton.tsx
- src/components/PostCard/TipModal.tsx
- src/components/Profile/EditInfoModal.tsx
- src/components/Profile/profileCard.tsx
- src/lib/hive/server-functions.ts
Some improvements on the PIX session.
- removed brazil location needed and update loading message
- now, the user can type 7 and the value will be set to 7.000 for hbd
- fix minimum 19.99 or 20.01 but its good to keep track of this error.
- qrcode blur improvements
- now, user select pix amount to purchase hbd, and get conversion to hbd at bottom of input
- , will be converted to .
- minor changes on SkateBank table
- reduce some useEffects
- removed unused variables
- changed pixbeedata to skatebank, but need refactor others variables
- set a placeholder for qrcode image when error so the screen keep aspect ratio
- removed debug console.logs
- improve some erros messages
- minnor changes on pix 
-  super long profile about that was not croping text and breaking out the box
| | |
|-|-| …
> Improvements on Wallet and Feed Tips Inputs

- src/components/Profile/profileCard.tsx
- src/components/Skater/SkaterHeader.tsx
- src/lib/hive/client-functions.ts
- src/lib/hive/server-functions.ts
This PR feat the Follow Button on Profile Card. Toogle Follow Unfollow and load initial following status when loading Card.
> Follow Button on Profile Card

- src/app/mainFeed/components/TokenSelector.tsx
new codes added
Token Price Fetch
Total Calculation in USD
https://github.com/user-attachments/assets/7389af4b-63ab-486a-8514-23ed5fa26be1
> high value of 1 dollar activates custom Message

- src/app/dao/components/ProposalDetailPanel.tsx
- src/app/dao/components/daoTreasure.tsx
- src/app/dao/components/proposalListItem.tsx
- src/app/mainFeed/components/CommentItem.tsx
- src/app/mainFeed/page.tsx
- src/app/mainFeed/utils/CarrouselRenderer.tsx
- src/app/upload/components/searchBar.tsx
- src/app/wallet/components/pix.tsx
- src/components/Magazine/test/page.tsx
- src/components/PostCard/HiveTipModal.tsx
- src/components/PostCard/TipButton.tsx
- src/components/PostModal/index.tsx
- src/components/Profile/profileCard.tsx
https://github.com/user-attachments/assets/b89c84d6-4da1-47c1-a160-6d259b03978e
> modifications to the modal tip and tip carousel

- src/app/mainFeed/utils/CarrouselRenderer.tsx
- src/app/post/ClientMarkdownRenderer.tsx
- src/components/Magazine/FullMagazineRenderers.tsx
- src/components/Magazine/MagazineRenderers.tsx
- src/components/Magazine/test/fullMag.tsx
- src/components/Magazine/test/page.tsx
- src/components/PostCard/Carousel.tsx
- src/lib/utils.ts
- src/utils/config.ts
fix ipfs.skatehive.app temporarily
> Ipfs correction

- src/app/dao/components/ProposalDetailPanel.tsx
- src/app/dao/components/proposalListItem.tsx
- src/app/mag/page.tsx
- src/app/mainFeed/components/CommentsList.tsx
- src/app/mainFeed/components/ToggleComments.tsx
- src/app/mainFeed/components/airdropModal.tsx
- src/app/upload/components/searchBar.tsx
- src/app/wallet/components/Modals/isHbdModalOpened.tsx
- src/app/wallet/components/Modals/isHiveModalsOpen.tsx
- src/app/wallet/components/hiveWallet.tsx
- src/components/MagColumn/index.tsx
- src/components/PostCard/TipButton.tsx
ps: this test is not in the code, it was just to show the text
> correction

- src/components/ButtonVoteComponent/HiveDataFetcher.tsx
- src/components/ButtonVoteComponent/VoteButton.tsx
- src/components/ButtonVoteComponent/VotingButton.tsx
In addition to the api problems, it is now saved in cache, and can use the upvote and downvote slider.
fixed downvotes and votes showing instantly, with new stylizations
https://github.com/user-attachments/assets/8038b8f2-7fc3-4ae5-9802-8a28b50e80fb
> problems with cache in the api fixed

- src/app/mainFeed/page.tsx
an unexpected bug happened with emojis, it was fixed and tested
> fix: correction of emoji appearing invisible

- src/app/mainFeed/components/AvatarList.tsx
- src/app/mainFeed/utils/CarrouselRenderer.tsx
- src/app/upload/components/searchBar.tsx
- src/components/AuthorAvatar.tsx
- src/lib/hive/client-functions.ts
here it was prevented from having multiple unnecessary and infinite requests, and also the carousel only loads when you click on a post or it is visible on the screen
> prevented multiple unnecessary requests, image and video loading prevented from loading before opening

- src/app/post/[...slug]/page.tsx
https://github.com/user-attachments/assets/15d3ff36-ab50-4429-9b50-b4db0b306fb1
> fix: post layout correction

- src/app/mainFeed/page.tsx
User Feedback Improvement with Persistent Toast
Low
Adding persistent "Processing" toast notifications to indicate post submission status.
Implements a persistent "Processing" toast during post submission. The toast remains visible while the post is being processed and is closed once the action is completed or failed. It also shows success or error toasts accordingly.
What kind of change is this?
Enhancement
Documentation changes needed?
No changes required for the documentation.
<table style="width: 100%; border: none; text-align: center;">
<tr>
<td>
<p>Processing Posting </p>
</td>
<td>
<p>Error Posting </p>
</td>
<td>
<p>Posting Success</p>
</td>
</tr>
</table>
Already tested:
The "Processing" toast appears correctly and remains active during post submission.
The toast closes when the …
> fix: correction in the feed, user with problem of not seeing post in the published feed

- src/app/wallet/components/Modals/isDepositHbdSavingsModalOpened.tsx
- src/app/wallet/components/Modals/isHPPowerModalOpened.tsx
- src/app/wallet/components/Modals/isHbdModalOpened.tsx
- src/app/wallet/components/Modals/isHiveModalsOpen.tsx
- src/app/wallet/components/hiveWallet.tsx
Here the wallet was fixed, showing the shipping methods and etc. of the wallet
> fix: wallet styling fixes

- src/app/mainFeed/page.tsx
- **File Upload Limit, Hive Power**
This update specifically addresses the file upload functionality and how it ties to a user's Hive Power.
---
- **Low**
The changes involve boundary checking and simple calculations, making the risks minimal. There is no direct interference with core functionalities.
---
- **plugin-goat**
The update stems from the need to integrate file upload limits that scale with user Hive Power.
---
- Introduces a **dynamic file upload size limit** calculated based on the user's Hive Power.
- Ensures users cannot upload files if their total size exceeds the calculated limit.
- Tracks the **total size of uploaded files** and adjusts dynamically, even allowing for cases where files are removed or new uploads occur.
---
- **Updates**
This is an enhancement to the …
> user limited to publishing file

- src/components/Hive/Keyboard.tsx
- src/components/Hive/Login/disconnectedModal.tsx
Users were complaining that they couldn't use capital letters to write, it was fixed
https://github.com/user-attachments/assets/1f66e398-8911-49af-881f-168492cc5eab
https://github.com/SkateHive/nextskateapp/pull/151/commits/63431ad1f247a8bbbaf4b0f382f11d927d479938
https://github.com/user-attachments/assets/f9ee26ad-9af4-4434-a167-91ec67b1d6ee
Now on mobile users can log in with the privatekey password by clicking the paste button
> feat: add Caps Lock functionality and improve Shift behavior

- src/app/dao/components/ProposalDetailPanel.tsx
Change:
Added overflowY="auto" to the Box component that displays the proposal content, allowing vertical scrolling when the content exceeds the defined height.
Objective:
Ensure that the user can scroll up and down and read the full content of the proposals.
> fix(proposal-view): add overflowY to enable scrolling

- src/app/notifications/components/TransactionHistory.tsx
Change: Fixed display of reward values ​​in TransactionHistory component
Objective: Ensure that HIVE, HBD and VESTS values ​​are displayed correctly
Pros:
- Improved readability of reward values
- Clear separation between different currency types
- More consistent UX
> fix: adjustment in reward calculation in TransactionHistory

- CONTRIBUTE.md
> Branders0n
